# Generated by Django 5.0.6 on 2024-06-18 19:24

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]