# Generated by Django 5.0.6 on 2024-06-18 20:40

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_create_pg_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_embedding',
            field=pgvector.django.VectorField(dimensions=512, null=True),
        ),
    ]
